"""Pre-built NLQ examples library for awsmap."""


_DISPLAY_NAMES = {
    "accessanalyzer": "Access Analyzer",
    "acm": "ACM (Certificates)",
    "apigateway": "API Gateway",
    "apigatewayv2": "API Gateway v2",
    "athena": "Athena",
    "autoscaling": "Auto Scaling",
    "backup": "Backup",
    "budgets": "Budgets",
    "cloudformation": "CloudFormation",
    "cloudfront": "CloudFront",
    "cloudtrail": "CloudTrail",
    "cloudwatch": "CloudWatch",
    "codebuild": "CodeBuild",
    "codedeploy": "CodeDeploy",
    "codepipeline": "CodePipeline",
    "cognito": "Cognito",
    "compute-optimizer": "Compute Optimizer",
    "config": "Config",
    "dynamodb": "DynamoDB",
    "ec2": "EC2",
    "ecr": "ECR",
    "ecs": "ECS",
    "elasticache": "ElastiCache",
    "elasticbeanstalk": "Elastic Beanstalk",
    "elbv2": "ELB (Load Balancers)",
    "events": "EventBridge",
    "general": "General (cross-service)",
    "glue": "Glue",
    "grafana": "Grafana",
    "iam": "IAM",
    "kms": "KMS",
    "lambda": "Lambda",
    "logs": "CloudWatch Logs",
    "mediaconvert": "MediaConvert",
    "organizations": "Organizations",
    "quicksight": "QuickSight",
    "ram": "RAM",
    "rds": "RDS",
    "resource-explorer-2": "Resource Explorer",
    "route53": "Route53",
    "s3": "S3",
    "secretsmanager": "Secrets Manager",
    "servicecatalog": "Service Catalog",
    "sns": "SNS",
    "sqs": "SQS",
    "ssm": "SSM",
    "sso": "SSO",
    "stepfunctions": "Step Functions",
    "timestream-influxdb": "Timestream InfluxDB",
    "vpc": "VPC",
    "wafv2": "WAF",
}


_EXAMPLES = {
    "accessanalyzer": [
        "count Access Analyzer analyzers per region",
        "show me Access Analyzer analyzers",
    ],
    "acm": [
        "count acm certificates in us-east-1",
        "count ACM certificates per account",
        "count ACM certificates per region",
        "count ACM certificates per status",
        "count ACM certificates per status in us-east-1",
        "count all acm resources",
        "find acm certificate",
        "get acm certificate count",
        "give me ACM certificates that are ISSUED",
        "list all acm certificate resources",
        "show me ACM certificates",
        "show me acm certificates in eu-west-1",
        "show me acm certificates in eu-west-3",
        "show me acm certificates in us-east-1",
        "show me ACM certificates in us-east-1 with status ISSUED",
        "show me ACM certificates in use",
        "show me ACM certificates not in use",
        "show me ACM certificates that are issued",
        "show me ACM certificates with DNS validation",
        "show me ACM certificates with status EXPIRED",
        "show me ACM certificates with status ISSUED",
        "show me all acm resources",
        "show me certs",
    ],
    "apigateway": [
        "count all apigateway resources",
        "count API Gateway API keys per region",
        "count API Gateway domain names per region",
        "count API Gateway REST APIs and API Gateway stages per region",
        "count API Gateway REST APIs per account",
        "count API Gateway REST APIs per region",
        "count API Gateway stages per region",
        "count apigateway api-keys in eu-west-1",
        "count apigateway usage-plans in eu-west-1",
        "find apigateway api-key",
        "find apigateway rest-api",
        "find apigateway stage",
        "find apigateway usage-plan",
        "get apigateway api-key count",
        "get apigateway rest-api count",
        "get apigateway stage count",
        "get apigateway usage-plan count",
        "give me the API Gateway usage plans",
        "how many API Gateway REST APIs per region",
        "list all apigateway api-key resources",
        "list all apigateway rest-api resources",
        "list all apigateway stage resources",
        "list all apigateway usage-plan resources",
        "show me all apigateway resources",
        "show me API Gateway API keys",
        "show me API Gateway API keys that are enabled",
        "show me API Gateway domain names",
        "show me API Gateway stages without tracing",
        "show me API Gateway usage plans",
        "show me API Gateway v2 domain names",
        "show me apigateway api-keys in eu-west-1",
        "show me apigateway usage-plans in eu-west-1",
        "show me CloudWatch log groups for API Gateway",
    ],
    "apigatewayv2": [
        "count all apigatewayv2 resources",
        "find apigatewayv2 domain-name",
        "get apigatewayv2 domain-name count",
        "list all apigatewayv2 domain-name resources",
        "show me all apigatewayv2 resources",
    ],
    "athena": [
        "count all athena resources",
        "count Athena named queries per account",
        "count Athena named queries per region",
        "count athena named-querys in eu-west-1",
        "find athena named-query",
        "get athena named-query count",
        "list all athena named-query resources",
        "list Athena named queries",
        "show me all athena resources",
        "show me Athena named queries",
        "show me athena named-querys in eu-west-1",
    ],
    "autoscaling": [
        "count all autoscaling resources",
        "find autoscaling auto-scaling-group",
        "get autoscaling auto-scaling-group count",
        "list all autoscaling auto-scaling-group resources",
        "show me all Auto Scaling groups",
        "show me all autoscaling resources",
        "show me Auto Scaling groups",
    ],
    "backup": [
        "count all backup resources",
        "count Backup vaults and Backup plans per region",
        "count Backup vaults per account",
        "count Backup vaults per region",
        "find backup vault",
        "get backup vault count",
        "how many Backup vaults per region",
        "list all backup vault resources",
        "list all Backup vaults",
        "show me all backup resources",
        "show me Backup vaults",
    ],
    "budgets": [
        "count all budgets resources",
        "count budgets per account",
        "find budgets budget",
        "find budgets budget-action",
        "get budgets budget count",
        "get budgets budget-action count",
        "list all budgets budget resources",
        "list all budgets budget-action resources",
        "show me all budgets resources",
        "show me AWS Budgets",
        "show me budget actions",
    ],
    "cloudformation": [
        "count all cloudformation resources",
        "count CloudFormation stacks and CloudTrail trails per region",
        "count cloudformation stacks in eu-west-1",
        "count CloudFormation stacks per account",
        "count CloudFormation stacks per region",
        "count CloudFormation stacks per status",
        "count CloudFormation stacks per status in us-east-1",
        "count CloudFormation stacks per status per region",
        "find cloudformation stack",
        "get cloudformation stack count",
        "how many CloudFormation stacks per region",
        "list all cloudformation stack resources",
        "list CloudFormation stacks",
        "list stacks in us-east-1",
        "show me all cloudformation resources",
        "show me CloudFormation stacks",
        "show me CloudFormation stacks in CREATE_COMPLETE status",
        "show me cloudformation stacks in eu-west-1",
        "show me cloudformation stacks in us-east-1",
        "show me CloudFormation stacks in us-east-1 with status CREATE_COMPLETE",
        "show me CloudFormation stacks sorted by status",
        "show me CloudFormation stacks with CREATE_COMPLETE status",
        "show me CloudFormation stacks with status UPDATE_IN_PROGRESS",
        "show me CloudFormation stacks without termination protection",
        "show me cloudformaton stacks",
        "what CloudFormation stacks have CREATE_COMPLETE status",
    ],
    "cloudfront": [
        "count all cloudfront resources",
        "count CloudFront distributions and cache policies per region",
        "count CloudFront distributions per account",
        "count CloudFront distributions per region",
        "count distributions per region",
        "find cloudfront distribution",
        "find CloudFront distributions that are enabled",
        "find cloudfront origin-access-control",
        "find cloudfront origin-access-identity",
        "get cloudfront distribution count",
        "get cloudfront origin-access-control count",
        "get cloudfront origin-access-identity count",
        "list all cloudfront distribution resources",
        "list all cloudfront origin-access-control resources",
        "list all cloudfront origin-access-identity resources",
        "show me all cloudfront distributions",
        "show me all cloudfront origin-access-controls",
        "show me all cloudfront origin-access-identitys",
        "show me all cloudfront resources",
        "show me all wafv2 web-acl-cloudfronts",
        "show me CloudFront distributions",
        "show me CloudFront distributions in global",
        "show me CloudFront distributions that are disabled",
        "show me CloudFront distributions that are enabled",
        "show me CloudFront distributions with status Deployed",
        "show me CloudFront origin access controls",
        "show me CloudFront origin access identities",
        "show me WAF CloudFront web ACLs",
        "what are my CloudFront distributions",
    ],
    "cloudtrail": [
        "are there any CloudTrail trails",
        "count all cloudtrail resources",
        "count cloudtrail trails in eu-west-1",
        "count CloudTrail trails per account",
        "count CloudTrail trails per region",
        "find cloudtrail trail",
        "get cloudtrail trail count",
        "list all cloudtrail trail resources",
        "show me all cloudtrail resources",
        "show me CloudTrail multi-region trails",
        "show me CloudTrail organization trails",
        "show me CloudTrail trails",
        "show me cloudtrail trails in eu-west-1",
        "show me CloudTrail trails that are logging",
        "show me CloudTrail trails that are not enabled",
        "show me CloudTrail trails that are not logging",
        "show me CloudTrail trails with log file validation enabled",
        "show me CloudTrail trails without log file validation",
    ],
    "cloudwatch": [
        "count all cloudwatch resources",
        "count CloudWatch alarms and dashboards per region",
        "count CloudWatch alarms per account",
        "count CloudWatch alarms per namespace",
        "count CloudWatch alarms per namespace in us-east-1",
        "count CloudWatch alarms per region",
        "count CloudWatch alarms per state",
        "count CloudWatch dashboards per account",
        "count CloudWatch dashboards per region",
        "count cloudwatch metric-alarms in eu-west-1",
        "find cloudwatch dashboard",
        "find cloudwatch metric-alarm",
        "get cloudwatch dashboard count",
        "get cloudwatch metric-alarm count",
        "give me all CloudWatch alarms",
        "how many CloudWatch dashboards exist",
        "list all cloudwatch dashboard resources",
        "list all cloudwatch metric-alarm resources",
        "show me all cloudwatch resources",
        "show me CloudWatch alarms",
        "show me CloudWatch alarms sorted by name",
        "show me CloudWatch alarms with evaluation_periods greater than 1",
        "show me CloudWatch alarms with state INSUFFICIENT_DATA",
        "show me CloudWatch alarms with state OK",
        "show me CloudWatch dashboards",
        "show me cloudwatch dashboards in ap-northeast-1",
        "show me cloudwatch dashboards in ap-northeast-2",
        "show me cloudwatch dashboards in ap-northeast-3",
        "show me cloudwatch dashboards in ap-south-1",
        "show me cloudwatch dashboards in ap-southeast-1",
        "show me cloudwatch dashboards in ap-southeast-2",
        "show me cloudwatch dashboards in ca-central-1",
        "show me cloudwatch dashboards in eu-central-1",
        "show me cloudwatch dashboards in eu-north-1",
        "show me cloudwatch dashboards in eu-west-1",
        "show me cloudwatch dashboards in eu-west-2",
        "show me cloudwatch dashboards in eu-west-3",
        "show me cloudwatch dashboards in sa-east-1",
        "show me cloudwatch dashboards in us-east-1",
        "show me cloudwatch dashboards in us-east-2",
        "show me cloudwatch dashboards in us-west-1",
        "show me cloudwatch dashboards in us-west-2",
        "show me CloudWatch log groups for Lambda functions",
        "show me CloudWatch log groups in eu-central-1",
        "show me CloudWatch log groups in eu-north-1",
        "show me CloudWatch log groups in us-east-1",
        "show me CloudWatch log groups without encryption",
        "show me CloudWatch log groups without retention",
        "show me CloudWatch metric alarms sorted by name",
        "show me cloudwatch metric-alarms in eu-west-1",
    ],
    "codebuild": [
        "count all codebuild resources",
        "count CodeBuild projects per account",
        "count CodeBuild projects per region",
        "find codebuild project",
        "get codebuild project count",
        "list all codebuild project resources",
        "show me all codebuild resources",
        "show me CodeBuild projects",
        "show me codebuild projects in eu-west-1",
        "what CodeBuild projects exist",
    ],
    "codedeploy": [
        "count all codedeploy resources",
        "count CodeDeploy applications per region",
        "count CodeDeploy deployment groups per region",
        "how many CodeDeploy applications per region",
        "show me all codedeploy resources",
        "show me CodeDeploy applications",
        "show me CodeDeploy deployment groups",
    ],
    "codepipeline": [
        "count all codepipeline resources",
        "count CodeBuild projects and CodePipeline pipelines per region",
        "count CodePipeline pipelines per account",
        "count CodePipeline pipelines per region",
        "count CodePipeline pipelines per status",
        "find all CodePipeline pipelines",
        "show me all codepipeline resources",
        "show me all pipelines",
        "show me CodePipeline pipelines",
    ],
    "cognito": [
        "count all cognito resources",
        "count Cognito user pools and Cognito identity pools per region",
        "count Cognito user pools per account",
        "count Cognito user pools per region",
        "list all Cognito user pools",
        "show me all cognito resources",
        "show me Cognito identity pools",
        "show me cognito identity-pools in eu-west-1",
        "show me Cognito user pool clients",
        "show me Cognito user pools",
    ],
    "compute-optimizer": [
        "show me Compute Optimizer Lambda recommendations",
    ],
    "config": [
        "count Config delivery channels per region",
        "count Config recorders and Config delivery channels per region",
        "count Config recorders per account",
        "count Config recorders per region",
        "show me Config configuration recorders",
        "show me config configuration-recorders in eu-west-1",
        "show me Config delivery channels",
        "show me config delivery-channels in eu-west-1",
        "show me Config recorders",
    ],
    "dynamodb": [
        "count all dynamodb resources",
        "count dynammo tables",
        "count DynamoDB streams per region",
        "count DynamoDB tables and DynamoDB streams per region",
        "count DynamoDB tables in ap-southeast-1 vs eu-central-1",
        "count dynamodb tables in eu-west-1",
        "count DynamoDB tables in sa-east-1 vs af-south-1",
        "count DynamoDB tables per account",
        "count DynamoDB tables per billing mode",
        "count DynamoDB tables per region",
        "count DynamoDB tables with stream enabled",
        "count DynamoDB tables without stream",
        "count Lambda functions and DynamoDB tables per region",
        "count S3 buckets and DynamoDB tables per region",
        "do I have any DynamoDB tables",
        "find DynamoDB tables in eu-west-1",
        "give me all DynamoDB tables",
        "how many DynamoDB tables do I have",
        "how many DynamoDB tables in ap-southeast-1",
        "how many DynamoDB tables in eu-west-1",
        "how many DynamoDB tables per region",
        "list DynamoDB tables",
        "list first 10 DynamoDB tables",
        "show me active DynamoDB tables",
        "show me all dynamodb resources",
        "show me DynamoDB streams",
        "show me dynamodb streams in eu-west-1",
        "show me DynamoDB streams with status ENABLED",
        "show me DynamoDB tables",
        "show me DynamoDB tables in eu-central-1",
        "show me dynamodb tables in eu-west-1",
        "show me DynamoDB tables in eu-west-1",
        "show me DynamoDB tables not in eu-central-1",
        "show me DynamoDB tables not in eu-west-1",
        "show me DynamoDB tables not in global",
        "show me DynamoDB tables not in us-east-1",
        "show me DynamoDB tables outside of eu-west-1",
        "show me DynamoDB tables sorted by name ascending",
        "show me DynamoDB tables sorted by region",
        "show me DynamoDB tables with billing mode PAY_PER_REQUEST",
        "show me DynamoDB tables with billing mode PROVISIONED",
        "show me DynamoDB tables with deletion protection",
        "show me DynamoDB tables with gsi_count greater than 0",
        "show me DynamoDB tables with item_count greater than 100",
        "show me DynamoDB tables with PAY_PER_REQUEST billing",
        "show me DynamoDB tables with PAY_PER_REQUEST billing mode",
        "show me DynamoDB tables with PROVISIONED billing",
        "show me DynamoDB tables with PROVISIONED billing mode",
        "show me DynamoDB tables with read_capacity greater than 5",
        "show me DynamoDB tables with status ACTIVE",
        "show me DynamoDB tables with stream enabled",
        "show me DynamoDB tables without deletion protection",
        "show me DynamoDB tables without encryption",
        "show me DynamoDB tables without global secondary indexes",
        "show me DynamoDB tables without point-in-time recovery",
        "show me DynamoDB tables without streams",
        "what DynamoDB tables are in eu-west-1",
        "what DynamoDB tables are outside eu-west-1",
        "what DynamoDB tables are there",
    ],
    "ec2": [
        "are there any unattached volumes",
        "count all ec2 resources",
        "count EBS volumes per account",
        "count EBS volumes per region",
        "count EBS volumes per state",
        "count EBS volumes per volume type",
        "count EBS volumes per volume type in us-east-1",
        "count EC2 instances and EBS volumes per region",
        "count EC2 instances and EC2 volumes per region",
        "count EC2 instances in eu-north-1 vs me-central-1",
        "count EC2 instances not in running state per region",
        "count EC2 instances per account",
        "count EC2 instances per instance type",
        "count EC2 instances per instance type in us-east-1",
        "count EC2 instances per platform",
        "count EC2 instances per region",
        "count EC2 instances per state",
        "count EC2 instances that are running per region",
        "count EC2 key pairs per account",
        "count EC2 key pairs per region",
        "count ec2 network-interfaces in us-east-1",
        "count ec2 security-groups in ap-northeast-1",
        "count ec2 security-groups in ap-northeast-2",
        "count ec2 security-groups in ap-northeast-3",
        "count ec2 security-groups in ap-southeast-1",
        "count ec2 security-groups in ap-southeast-2",
        "count ec2 security-groups in ca-central-1",
        "count ec2 security-groups in eu-central-1",
        "count ec2 security-groups in eu-west-1",
        "count ec2 security-groups in eu-west-3",
        "count ec2 security-groups in sa-east-1",
        "count ec2 security-groups in us-east-1",
        "count ec2 security-groups in us-east-2",
        "count ec2 security-groups in us-west-1",
        "count ec2 security-groups in us-west-2",
        "count Elastic IPs and network interfaces per region",
        "count Elastic IPs per account",
        "count Elastic IPs per region",
        "count key pairs",
        "count network interfaces per account",
        "count network interfaces per region",
        "count security groups and network ACLs per region",
        "count security groups per account",
        "count security groups per region",
        "count securty groups",
        "find EC2 instances",
        "find security groups in eu-west-1",
        "give me all EBS volumes",
        "give me all security groups in eu-west-1",
        "give me the security groups",
        "how many disks",
        "how many EBS volumes are unattached",
        "how many EC2 instances in ca-central-1",
        "how many EC2 instances in ca-central-1 vs sa-east-1",
        "how many EC2 instances per account and per type",
        "how many EC2 resources per region and per type",
        "how many security groups in eu-west-1",
        "how many security groups per region",
        "is there any EC2 instance",
        "list security groups",
        "show me all ec2 resources",
        "show me EBS volumes",
        "show me EBS volumes with encryption enabled",
        "show me EBS volumes with iops greater than 3000",
        "show me EBS volumes with state in-use",
        "show me EBS volumes with storage type gp3",
        "show me EBS volumes with volume type gp2",
        "show me EBS volumes with volume type gp2 that are unattached",
        "show me EBS volumes with volume type gp3",
        "show me EBS volumes without encryption",
        "show me EBS volumes without encryption in us-east-1",
        "show me ec2 instaces",
        "show me EC2 instances",
        "show me ec2 instances in us-east-1",
        "show me EC2 instances in us-east-1 that are running sorted by name",
        "show me EC2 instances in us-east-1 with state running",
        "show me EC2 instances not in running state",
        "show me EC2 instances not tagged with Team",
        "show me EC2 instances sorted by instance type",
        "show me EC2 instances sorted by name",
        "show me EC2 instances sorted by region and name",
        "show me EC2 instances that are stopped",
        "show me EC2 instances with architecture arm64",
        "show me EC2 instances with architecture x86_64",
        "show me EC2 instances with public IP addresses",
        "show me EC2 instances with state running",
        "show me EC2 instances with state stopped",
        "show me EC2 instances without public IP",
        "show me EC2 key pairs",
        "show me ec2 network-interfaces in us-east-1",
        "show me ec2 security-groups in ap-northeast-1",
        "show me ec2 security-groups in ap-northeast-2",
        "show me ec2 security-groups in ap-northeast-3",
        "show me ec2 security-groups in ap-south-1",
        "show me ec2 security-groups in ap-southeast-1",
        "show me ec2 security-groups in ap-southeast-2",
        "show me ec2 security-groups in ca-central-1",
        "show me ec2 security-groups in eu-central-1",
        "show me ec2 security-groups in eu-north-1",
        "show me ec2 security-groups in eu-west-1",
        "show me ec2 security-groups in eu-west-2",
        "show me ec2 security-groups in eu-west-3",
        "show me ec2 security-groups in sa-east-1",
        "show me ec2 security-groups in us-east-1",
        "show me ec2 security-groups in us-east-2",
        "show me ec2 security-groups in us-west-1",
        "show me ec2 security-groups in us-west-2",
        "show me ec2 volumes in us-east-1",
        "show me elastic IPs",
        "show me first 20 EC2 instances",
        "show me first 50 EC2 instances",
        "show me network interfaces",
        "show me security groups",
        "show me security groups allowing access from 0.0.0.0/0",
        "show me security groups in ap-northeast-1",
        "show me security groups in ap-northeast-2",
        "show me security groups in ap-northeast-3",
        "show me security groups in ap-south-1",
        "show me security groups in ap-southeast-1",
        "show me security groups in ap-southeast-2",
        "show me security groups in ca-central-1",
        "show me security groups in eu-central-1",
        "show me security groups in eu-central-2",
        "show me security groups in eu-north-1",
        "show me security groups in eu-west-3",
        "show me security groups with ingress rules",
        "show me security groups with no ingress rules",
        "show me stopped EC2 instances",
        "show me stopped EC2 instances in eu-west-1",
        "show me stopped EC2 instances in us-east-1",
        "show me unused elastic IPs",
        "what security groups exist",
        "which EC2 instances are stopped",
    ],
    "ecr": [
        "count all ecr resources",
        "count all ecr-public resources",
        "count ECR repositories per account",
        "count ECR repositories per region",
        "list ECR public repositories",
        "show me all ecr resources",
        "show me all ecr-public resources",
        "show me ECR public repositories",
        "show me ECR repos with image tag mutability IMMUTABLE",
        "show me ECR repositories",
        "show me ECR repositories with image tag mutability IMMUTABLE",
    ],
    "ecs": [
        "count all ecs resources",
        "count ECS clusters and ECS services per region",
        "count ECS clusters and ECS task definitions per region",
        "count ECS clusters per account",
        "count ECS clusters per region",
        "count ECS services and ECS tasks per region",
        "count ECS services per cluster",
        "count ECS task definitions per region",
        "give me all ECS clusters",
        "how many ECS services per region",
        "list all containers",
        "show me all ecs resources",
        "show me ECS clusters in us-east-1",
        "show me ECS clusters with active services greater than 0",
        "show me ECS clusters with running_tasks_count greater than 0",
        "show me ECS services with EC2 launch type",
        "show me ECS services with FARGATE launch type",
        "show me ECS services with scheduling strategy REPLICA",
        "show me ECS task definitions",
        "show me ECS task definitions with status ACTIVE",
        "show me ecs task-definitions in eu-west-1",
    ],
    "elasticache": [
        "count all elasticache resources",
        "count ElastiCache clusters per engine",
        "count ElastiCache clusters per region",
        "how many ElastiCache clusters per account",
        "show me all ElastiCache clusters",
        "show me all elasticache resources",
        "show me ElastiCache clusters",
        "show me ElastiCache clusters not using redis",
        "show me ElastiCache clusters using memcached",
        "show me ElastiCache clusters using redis",
        "show me ElastiCache clusters using redis engine",
        "show me ElastiCache using redis",
    ],
    "elasticbeanstalk": [
        "show me Elastic Beanstalk applications",
    ],
    "elbv2": [
        "count ELB load balancers and target groups per region",
        "count ELB target groups per account",
        "count ELB target groups per region",
        "show me all application load balancers",
        "show me ELB target groups",
        "show me load balancers",
    ],
    "events": [
        "count EventBridge rules per account",
        "count EventBridge rules per region",
        "count EventBridge rules per state",
        "show me event rules",
        "show me EventBridge rules",
        "show me EventBridge rules that are enabled",
        "show me EventBridge rules with schedule expression",
        "show me EventBridge rules with state ENABLED",
        "show me EventBridge rules without schedule expression",
    ],
    "general": [
        "count all accessanalyzer resources",
        "count all AWS resources",
        "count all compute-optimizer resources",
        "count all config resources",
        "count all elasticbeanstalk resources",
        "count all elbv2 resources",
        "count all events resources",
        "count all logs resources",
        "count all resource-explorer-2 resources",
        "count all resources per account per service",
        "count all servicecatalog resources",
        "count all stepfunctions resources",
        "count events rules in eu-west-1",
        "count global resources per service",
        "count global resources per type",
        "count resources by region",
        "count resources by service",
        "count resources by type",
        "count resources in ap-northeast-1",
        "count resources in ap-northeast-2",
        "count resources in ap-northeast-3",
        "count resources in ap-south-1",
        "count resources in ap-southeast-1",
        "count resources in ap-southeast-2",
        "count resources in ca-central-1",
        "count resources in eu-central-1",
        "count resources in eu-central-1 per service",
        "count resources in eu-north-1",
        "count resources in eu-west-1",
        "count resources in eu-west-3",
        "count resources in sa-east-1",
        "count resources in us-east-1",
        "count resources in us-east-2",
        "count resources in us-west-2",
        "count resources not tagged with Environment per service",
        "count resources per account",
        "count resources per account across all regions",
        "count resources per account and per service",
        "count resources per Environment tag",
        "count resources per Owner tag",
        "count resources per Project tag",
        "count resources per service",
        "count resources per service in us-east-1",
        "count resources tagged with Environment per region",
        "count resources with empty description per service",
        "count resources with no tags",
        "find accessanalyzer analyzer",
        "find resources not tagged with Environment",
        "find resources tagged with Environment or Owner",
        "find resources tagged with Owner or Team",
        "get accessanalyzer analyzer count",
        "give me resources not in global",
        "how many accounts in my organization",
        "how many resources per account",
        "how many resources per account and per region",
        "how many resources per account and per service",
        "how many resources per account and per type",
        "how many resources per region",
        "how many resources per region and per service",
        "how many resources per service",
        "how many total resources across all accounts",
        "list all accessanalyzer analyzer resources",
        "list all resources in eu-west-3",
        "list all resources per service per region",
        "show me accessanalyzer analyzers in us-east-1",
        "show me all accessanalyzer resources",
        "show me all AWS resources",
        "show me all compute-optimizer resources",
        "show me all config resources",
        "show me all elasticbeanstalk resources",
        "show me all elbv2 resources",
        "show me all events resources",
        "show me all global resources",
        "show me all logs resources",
        "show me all resource-explorer-2 resources",
        "show me all resources in ap-northeast-1",
        "show me all resources in ap-northeast-2",
        "show me all resources in ap-northeast-3",
        "show me all resources in ap-south-1",
        "show me all resources in ap-southeast-1",
        "show me all resources in ap-southeast-2",
        "show me all resources in ca-central-1",
        "show me all resources in eu-central-1",
        "show me all resources in eu-north-1",
        "show me all resources in eu-west-1",
        "show me all resources in eu-west-3",
        "show me all resources in sa-east-1",
        "show me all resources in us-east-1",
        "show me all resources in us-east-2",
        "show me all resources in us-west-2",
        "show me all servicecatalog resources",
        "show me all stepfunctions resources",
        "show me events rules in eu-west-1",
        "show me everything in us-east-1",
        "show me resource-explorer-2 indexs in eu-west-1",
        "show me resource-explorer-2 views in eu-west-1",
        "show me resources in ap-southeast-1",
        "show me resources in ca-central-1",
        "show me resources in eu-central-1",
        "show me resources in global region",
        "show me resources in sa-east-1",
        "show me resources in us-east-1 or us-west-2",
        "show me resources in us-west-2",
        "show me resources not tagged with Environment",
        "show me resources not tagged with Owner",
        "show me resources not tagged with Project",
        "show me resources not tagged with Team",
        "show me resources tagged with Owner",
        "show me resources tagged with Project",
        "show me resources tagged with Service",
        "show me resources with 3 or more tags",
        "show me resources with 5 or more tags",
        "show me resources with empty description",
        "show me resources without a CostCenter tag",
        "show me resources without any tags",
        "show me top 100 resources by region",
        "total number of resources",
        "what resources exist in ap-southeast-1",
        "which resources have a Name tag",
        "which service has the most resources",
    ],
    "glue": [
        "count all glue resources",
        "count Glue databases and Glue jobs per region",
        "count Glue databases per account",
        "count Glue databases per region",
        "count Glue jobs and Glue crawlers per region",
        "count Glue jobs per account",
        "count Glue jobs per region",
        "do I have any Glue jobs",
        "find Glue jobs",
        "how many Glue jobs per region",
        "show me all glue resources",
        "show me Glue databases",
        "show me glue databases in eu-west-1",
        "show me Glue jobs",
    ],
    "grafana": [
        "are there any Grafana workspaces",
        "count all grafana resources",
        "count Grafana workspaces per region",
        "show me all grafana resources",
        "show me Grafana workspaces",
    ],
    "iam": [
        "count all iam resources",
        "count IAM groups per account",
        "count IAM instance profiles and IAM groups per region",
        "count IAM policies per account",
        "count IAM policies per region",
        "count IAM roles",
        "count IAM roles and IAM users per region",
        "count IAM roles in global vs global",
        "count IAM roles per account",
        "count IAM roles per path",
        "count IAM roles per region",
        "count IAM users and IAM roles per account",
        "count IAM users per account",
        "count the IAM roles",
        "find IAM users",
        "give me the IAM roles",
        "give me the IAM roles in global",
        "give me the IAM users",
        "how many IAM instance profiles per account",
        "how many IAM roles exist",
        "how many IAM users are there",
        "list IAM roles",
        "list IAM users sorted by account and region",
        "show me all iam groups",
        "show me all iam instance-profiles",
        "show me all IAM policies",
        "show me all iam policys",
        "show me all iam resources",
        "show me all IAM roles",
        "show me all iam roles",
        "show me all iam saml-providers",
        "show me all IAM users",
        "show me all iam users",
        "show me IAM groups",
        "show me IAM instance profiles",
        "show me IAM instance profiles with roles",
        "show me IAM policies",
        "show me IAM policies in global",
        "show me IAM policies that are attachable",
        "show me IAM policies that are not attached",
        "show me IAM policies with attachment_count 0",
        "show me IAM policies with attachment_count greater than 0",
        "show me IAM policies with attachment_count greater than 0 in global",
        "show me IAM policies with path /",
        "show me iam roels",
        "show me IAM roles",
        "show me IAM roles created in the last year",
        "show me IAM roles in global",
        "show me IAM roles with custom path",
        "show me IAM roles with max session duration greater than 3600",
        "show me IAM roles with path /",
        "show me IAM roles with path /aws-service-role/",
        "show me IAM roles with path /service-role/",
        "show me IAM roles without admin",
        "show me IAM SAML providers",
        "show me IAM users",
        "show me IAM users and their attached policies",
        "show me IAM users in global",
        "show me IAM users not in any groups",
        "show me IAM users who have admin permissions",
        "show me IAM users with access keys",
        "show me IAM users with access_keys_count 0",
        "show me IAM users with access_keys_count 1",
        "show me IAM users with access_keys_count greater than 0 without MFA",
        "show me IAM users with MFA enabled",
        "show me IAM users with path /",
        "show me IAM users without access keys",
        "show me IAM users without admin policies",
        "show me IAM users without console access",
        "show me IAM users without MFA",
        "show me IAM users without MFA enabled",
        "what IAM policies are defined",
        "what IAM roles contain admin in the name",
    ],
    "kms": [
        "count all kms resources",
        "count KMS keys and KMS aliases per region",
        "count KMS keys per account",
        "count KMS keys per region",
        "list all KMS keys",
        "show me all kms resources",
        "show me KMS aliases",
        "show me kms aliass in eu-west-1",
        "show me KMS keys that are enabled",
        "show me KMS keys with state Enabled",
    ],
    "lambda": [
        "are there any Lambda functions in eu-central-1",
        "count all lambda resources",
        "count compute-optimizer lambda-recommendations in eu-west-1",
        "count ECR repositories and Lambda layers per region",
        "count Lambda event source mappings per region",
        "count lambda event-source-mappings in eu-west-1",
        "count Lambda functions and Lambda layers per region",
        "count Lambda functions and log groups per region",
        "count Lambda functions and S3 buckets in eu-west-1 per service",
        "count Lambda functions and S3 buckets per region",
        "count Lambda functions in eu-west-1",
        "count lambda functions in eu-west-1",
        "count Lambda functions in us-east-1",
        "count Lambda functions in us-east-1 using python per runtime",
        "count Lambda functions not using nodejs per region",
        "count Lambda functions not using python per region",
        "count Lambda functions per account",
        "count Lambda functions per architecture",
        "count Lambda functions per package type",
        "count Lambda functions per region",
        "count Lambda functions per runtime",
        "count Lambda functions per runtime and memory combination",
        "count Lambda functions per runtime in eu-west-1 with timeout greater than 30",
        "count Lambda functions per runtime in us-east-1",
        "count Lambda functions using python3.12 in eu-west-1",
        "count Lambda functions using python3.12 per region",
        "count Lambda functions using rust runtime per region",
        "count Lambda functions with timeout less than 30 seconds",
        "count lambda layers in eu-west-1",
        "count Lambda layers per account",
        "count Lambda layers per region",
        "find all Lambda functions",
        "find Lambda functions",
        "find Lambda functions with python3.12 runtime",
        "find Lambda functions with timeout greater than 60",
        "find lamda layers",
        "give me all Lambda functions",
        "how many Lambda functions are there",
        "how many Lambda functions exist",
        "how many Lambda functions in us-east-1 vs eu-west-1",
        "how many Lambda functions per account",
        "how many Lambda functions per account and per runtime",
        "how many Lambda functions per region",
        "how many Lambda functions per region and per account",
        "how many Lambda functions per region and per runtime",
        "is there any Lambda function in us-east-1",
        "list Lambda functions in eu-central-1",
        "list Lambda functions not in eu-west-1",
        "list Lambda functions with python3.9 runtime",
        "show me 10 most recent Lambda functions",
        "show me all lambda resources",
        "show me compute-optimizer lambda-recommendations in eu-west-1",
        "show me IAM roles for Lambda service",
        "show me Lambda event source mappings",
        "show me lambda event-source-mappings in eu-west-1",
        "show me lambda functions",
        "show me Lambda functions across all accounts and regions",
        "show me Lambda functions excluding timeout greater than 60",
        "show me Lambda functions in eu-central-1",
        "show me lambda functions in eu-west-1",
        "show me Lambda functions in eu-west-1",
        "show me Lambda functions in eu-west-1 or eu-central-1",
        "show me Lambda functions in eu-west-1 using python3.12 sorted by memory",
        "show me Lambda functions in eu-west-1 using python3.12 with timeout greater than 60",
        "show me Lambda functions in eu-west-1 with python runtime",
        "show me Lambda functions in us-east-1",
        "show me Lambda functions in us-east-1 using nodejs",
        "show me Lambda functions not in ap-south-1",
        "show me Lambda functions not in us-east-1",
        "show me Lambda functions not tagged with Environment",
        "show me Lambda functions not using python runtime",
        "show me Lambda functions sorted by memory ascending",
        "show me Lambda functions sorted by memory descending",
        "show me Lambda functions sorted by name descending",
        "show me Lambda functions sorted by region",
        "show me Lambda functions sorted by timeout",
        "show me Lambda functions tagged with Environment",
        "show me Lambda functions using nodejs runtime",
        "show me Lambda functions using nodejs22.x runtime",
        "show me Lambda functions using python in eu-west-1 with timeout greater than 30",
        "show me Lambda functions using python2.7 runtime",
        "show me Lambda functions using python3.10 runtime",
        "show me Lambda functions using python3.12 runtime",
        "show me Lambda functions using python3.13 runtime",
        "show me Lambda functions using python3.8 runtime",
        "show me Lambda functions using python3.9 runtime",
        "show me Lambda functions using rust runtime per region",
        "show me Lambda functions with code size greater than 1000000",
        "show me Lambda functions with ephemeral storage greater than 512",
        "show me Lambda functions with memory between 512 and 2048",
        "show me Lambda functions with no dead letter queue",
        "show me Lambda functions with no VPC configuration",
        "show me Lambda functions with package type Image",
        "show me Lambda functions with package type Zip",
        "show me Lambda functions with package type Zip and x86_64 architecture",
        "show me Lambda functions with timeout between 30 and 60 seconds",
        "show me Lambda functions with timeout greater than 120",
        "show me Lambda functions with timeout greater than 30",
        "show me Lambda functions with timeout greater than 30 and memory less than 512",
        "show me Lambda functions with timeout greater than 30 seconds in eu-west-1",
        "show me Lambda functions with timeout greater than 300 seconds",
        "show me Lambda functions with timeout less than 10",
        "show me Lambda functions with x86_64 architecture",
        "show me Lambda functions without dead letter queue configured",
        "show me Lambda functions without environment variables",
        "show me Lambda functions without reserved concurrency",
        "show me Lambda layers",
        "show me lambda layers in eu-west-1",
        "show me lamda functions",
        "show me top 10 Lambda functions by memory",
        "show me top 5 Lambda functions by memory",
        "what Lambda functions are in eu-west-1",
        "what Lambda functions exist",
        "which accounts have Lambda functions",
        "which accounts have Lambda functions in eu-west-1",
        "which Lambda functions use python3.9",
        "which regions have Lambda functions",
        "which regions have the most Lambda functions",
    ],
    "logs": [
        "count log groups per account",
        "count log groups per region",
        "count log groups per retention period",
        "count log groups per retention period in us-east-1",
        "count logs log-groups in eu-west-1",
        "find all log groups",
        "how many log groups are there",
        "show me log groups",
        "show me log groups in us-east-1 without retention policy",
        "show me log groups sorted by name",
        "show me log groups with metric_filter_count greater than 0",
        "show me log groups with retention period less than 7 days",
        "show me log groups with stored bytes greater than 1000000",
        "show me log groups without retention policy",
        "show me logs log-groups in eu-central-1",
        "show me logs log-groups in eu-west-1",
        "show me logs log-groups in us-east-1",
    ],
    "mediaconvert": [
        "count all mediaconvert resources",
        "count MediaConvert job templates per region",
        "show me all mediaconvert resources",
        "show me MediaConvert job templates",
    ],
    "organizations": [
        "count all organizations resources",
        "list organizations accounts that are ACTIVE",
        "show me all organization accounts",
        "show me all organizations accounts",
        "show me all organizations organizations",
        "show me all organizations resources",
        "show me organizations accounts",
        "show me Organizations accounts in global",
        "show me organizations accounts with ACTIVE status",
        "show me Organizations accounts with status ACTIVE",
        "show me Organizations organization",
        "show me Organizations organizational units",
        "show me Organizations policies",
        "show me Organizations roots",
    ],
    "quicksight": [
        "count all quicksight resources",
        "count quicksight analysiss in eu-west-1",
        "count quicksight data-sets in eu-west-1",
        "count quicksight data-sources in eu-west-1",
        "count QuickSight datasets per account",
        "show me all quicksight resources",
        "show me QuickSight analyses",
        "show me quicksight analysiss in eu-west-1",
        "show me QuickSight data sources",
        "show me quicksight data-sets in eu-west-1",
        "show me quicksight data-sources in eu-west-1",
        "show me QuickSight datasets",
    ],
    "ram": [
        "count all ram resources",
        "count RAM resource shares per account",
        "show me all ram resources",
        "show me RAM resource shares",
    ],
    "rds": [
        "count all rds resources",
        "count EC2 instances and RDS instances per region",
        "count RDS instances and RDS clusters per region",
        "count RDS instances in us-gov-east-1 vs us-gov-west-1",
        "count RDS instances per engine",
        "count RDS instances per engine per region",
        "count RDS instances using aurora per region",
        "count RDS instances using mysql per region",
        "count RDS instances using postgres per engine",
        "count RDS instances using postgres per region",
        "count RDS instances with multi-AZ enabled per engine per region",
        "how many RDS instances in us-east-1 versus eu-west-1",
        "how many RDS instances per region",
        "show me all rds resources",
        "show me my databases",
        "show me RDS database instances",
        "show me RDS db subnet groups",
        "show me rds db-subnet-groups in eu-west-1",
        "show me rds instaces",
        "show me RDS instances not using aurora",
        "show me RDS instances not using mysql",
        "show me RDS instances sorted by engine",
        "show me RDS instances using aurora",
        "show me RDS instances using mariadb",
        "show me RDS instances using MariaDB",
        "show me RDS instances using mysql",
        "show me RDS instances using Oracle",
        "show me RDS instances using oracle",
        "show me RDS instances using postgres",
        "show me RDS instances using SQL Server",
        "show me RDS instances using sqlserver",
        "show me RDS instances with allocated_storage greater than 50",
        "show me RDS instances with multi-AZ disabled",
        "show me RDS instances with multi-AZ enabled",
        "show me RDS instances with mysql engine",
        "show me RDS instances with postgres engine",
        "show me RDS instances with storage type gp3",
        "show me RDS instances without encryption",
        "show me RDS subnet groups",
        "which regions have RDS instances",
    ],
    "resource-explorer-2": [
        "show me Resource Explorer indexes",
        "show me Resource Explorer views",
    ],
    "route53": [
        "count ACM certificates and Route53 hosted zones per region",
        "count all route53 resources",
        "count all route53domains resources",
        "count Route53 hosted zones per account",
        "how many Route53 hosted zones do I have",
        "how many Route53 hosted zones per account",
        "show me all Route 53 hosted zones",
        "show me all route53 hosted-zones",
        "show me all route53 resources",
        "show me all route53domains domains",
        "show me all route53domains resources",
        "show me dns zones",
        "show me Route53 domains in global",
        "show me Route53 hosted zones",
        "show me Route53 hosted zones in global",
        "show me Route53 hosted zones with record_count greater than 10",
        "show me Route53 public hosted zones",
        "show me Route53 registered domains",
    ],
    "s3": [
        "count all s3 resources",
        "count S3 buckets",
        "count s3 buckets in eu-west-1",
        "count s3 buckets in us-east-1",
        "count S3 buckets per account",
        "count S3 buckets per region",
        "count S3 buckets per region and per account",
        "count S3 buckets per versioning status",
        "count S3 buckets per versioning status in us-east-1",
        "count S3 buckets per versioning status per region",
        "count S3 buckets with versioning enabled",
        "count S3 buckets without versioning per region",
        "do I have any public S3 buckets",
        "do I have any S3 buckets",
        "find S3 buckets in eu-west-1",
        "find S3 buckets not in us-east-1",
        "give me S3 buckets in eu-west-1",
        "give me the S3 buckets",
        "how many S3 buckets are public",
        "how many S3 buckets do I have",
        "how many S3 buckets in eu-west-1",
        "how many S3 buckets in us-west-2",
        "how many S3 buckets per account",
        "list all S3 buckets",
        "list first 5 S3 buckets",
        "list S3 buckets in us-east-1",
        "list s3 bukets",
        "show me all s3 resources",
        "show me private S3 buckets",
        "show me public S3 buckets",
        "show me public S3 buckets in us-east-1 with AES256 encryption",
        "show me S3 buckets",
        "show me S3 buckets created after 2024",
        "show me S3 buckets in ap-southeast-1",
        "show me s3 buckets in ap-southeast-1",
        "show me S3 buckets in eu-central-1",
        "show me S3 buckets in eu-central-1 with versioning enabled sorted by name",
        "show me s3 buckets in eu-west-1",
        "show me S3 buckets in multiple accounts",
        "show me S3 buckets in us-east-1",
        "show me s3 buckets in us-east-1",
        "show me S3 buckets in us-east-1 that are private",
        "show me S3 buckets in us-east-1 that are public",
        "show me S3 buckets in us-east-1 with versioning",
        "show me S3 buckets in us-east-1 with versioning Enabled",
        "show me S3 buckets in us-east-1 with versioning Enabled sorted by name",
        "show me S3 buckets not in eu-west-1 or eu-central-1",
        "show me S3 buckets not in us-west-1 or us-west-2",
        "show me S3 buckets not tagged with Owner",
        "show me S3 buckets outside us-east-1",
        "show me S3 buckets sorted by name",
        "show me S3 buckets sorted by name ascending",
        "show me S3 buckets sorted by region ascending",
        "show me S3 buckets tagged with Owner",
        "show me S3 buckets with AES256 encryption",
        "show me S3 buckets with AES256 encryption in eu-west-1",
        "show me S3 buckets with encryption configured",
        "show me S3 buckets with server-side encryption",
        "show me S3 buckets with tags configured",
        "show me S3 buckets with versioning enabled",
        "show me S3 buckets with versioning Enabled",
        "show me S3 buckets with versioning Suspended",
        "show me S3 buckets with versioning suspended",
        "show me S3 buckets without lifecycle policies",
        "show me S3 buckets without logging",
        "show me S3 buckets without object lock",
        "show me S3 buckets without replication",
        "show me S3 buckets without tags in us-east-1",
        "show me S3 buckets without versioning",
        "show me S3 buckets without versioning and without encryption",
        "show me top 20 S3 buckets by name",
        "what S3 buckets do I have",
        "which regions have S3 buckets",
        "which S3 buckets are public",
        "which S3 buckets have versioning enabled",
    ],
    "secretsmanager": [
        "count all secretsmanager resources",
        "count KMS keys and Secrets Manager secrets per region",
        "count Secrets Manager secrets per account",
        "count Secrets Manager secrets per region",
        "count secretsmanager secrets in eu-west-1",
        "find my secrets",
        "show me all secretsmanager resources",
        "show me secrets in secrets manager",
        "show me Secrets Manager secrets",
        "show me Secrets Manager secrets in us-east-1",
        "show me Secrets Manager secrets without rotation",
        "show me secretsmanager secrets in eu-west-1",
    ],
    "servicecatalog": [
        "show me Service Catalog products",
    ],
    "sns": [
        "count all sns resources",
        "count sns subscriptions in eu-west-1",
        "count SNS topics and SNS subscriptions per region",
        "count sns topics in eu-west-1",
        "count SNS topics per account",
        "count SNS topics per region",
        "give me the SNS topics",
        "how many SNS subscriptions per region",
        "how many SNS topics per region",
        "list SNS topics",
        "list topics",
        "show me all sns resources",
        "show me SNS subscriptions",
        "show me sns subscriptions in eu-west-1",
        "show me SNS topics",
        "show me sns topics in eu-west-1",
        "show me SNS topics in us-east-1",
        "show me SNS topics that are standard",
    ],
    "sqs": [
        "are there any SQS queues",
        "count all sqs resources",
        "count SNS topics and SQS queues per region",
        "count sqs queues in eu-west-1",
        "count SQS queues per account",
        "count SQS queues per region",
        "find my queues",
        "how many SNS topics and SQS queues per region",
        "show me all sqs resources",
        "show me SQS queues",
        "show me sqs queues in eu-west-1",
        "show me SQS queues that are standard",
        "show me SQS queues with approximate_messages greater than 0",
        "show me SQS queues with dead letter target configured",
        "show me SQS queues with standard type",
        "show me SQS queues with visibility timeout greater than 30",
        "what SQS queues do I have",
    ],
    "ssm": [
        "count all ssm resources",
        "count SSM associations per region",
        "count SSM documents per region",
        "count SSM parameters and SSM documents per region",
        "count SSM parameters per account",
        "count SSM parameters per region",
        "show me all ssm resources",
        "show me SSM associations",
        "show me SSM documents",
        "show me Systems Manager parameters",
    ],
    "sso": [
        "count all sso resources",
        "count sso instances in eu-west-1",
        "count SSO permission sets per account",
        "count sso users in eu-west-1",
        "give me the SSO permission sets",
        "show me all sso resources",
        "show me SSO instances",
        "show me sso instances in eu-west-1",
        "show me SSO permission sets",
        "show me sso permission-sets in eu-west-1",
        "show me SSO users",
        "show me sso users in eu-west-1",
    ],
    "stepfunctions": [
        "count Step Functions and EventBridge rules per account",
        "count Step Functions and EventBridge rules per region",
        "count Step Functions in ca-central-1 vs eu-south-1",
        "count Step Functions per account",
        "count Step Functions per region",
        "count Step Functions per status",
        "give me the Step Functions state machines",
        "how many Step Functions per region",
        "show me Step Functions executions with status TIMED_OUT",
        "show me Step Functions state machines",
        "show me Step Functions with status ACTIVE",
        "show me Step Functions with type STANDARD",
    ],
    "timestream-influxdb": [
        "count all timestream-influxdb resources",
        "show me all timestream-influxdb resources",
        "show me Timestream InfluxDB parameter groups",
    ],
    "vpc": [
        "count all vpc resources",
        "count DHCP options per region",
        "count internet gateways and route tables per region",
        "count internet gateways per account",
        "count internet gateways per region",
        "count network ACLs per account",
        "count route tables per account",
        "count route tables per region",
        "count subnets per account",
        "count subnets per availability zone",
        "count subnets per availability zone in us-east-1",
        "count subnets per region",
        "count vpc dhcp-optionss in ap-northeast-1",
        "count vpc dhcp-optionss in ap-northeast-2",
        "count vpc dhcp-optionss in ap-northeast-3",
        "count vpc dhcp-optionss in ap-south-1",
        "count vpc dhcp-optionss in ap-southeast-1",
        "count vpc dhcp-optionss in ap-southeast-2",
        "count vpc dhcp-optionss in ca-central-1",
        "count vpc dhcp-optionss in eu-central-1",
        "count vpc dhcp-optionss in eu-north-1",
        "count vpc dhcp-optionss in eu-west-1",
        "count vpc dhcp-optionss in eu-west-2",
        "count vpc dhcp-optionss in eu-west-3",
        "count vpc dhcp-optionss in sa-east-1",
        "count vpc dhcp-optionss in us-east-1",
        "count vpc dhcp-optionss in us-east-2",
        "count vpc dhcp-optionss in us-west-1",
        "count vpc dhcp-optionss in us-west-2",
        "count VPC endpoints per account",
        "count VPC endpoints per region",
        "count vpc internet-gateways in ap-northeast-1",
        "count vpc internet-gateways in ap-northeast-2",
        "count vpc internet-gateways in ap-northeast-3",
        "count vpc internet-gateways in ap-southeast-1",
        "count vpc internet-gateways in ap-southeast-2",
        "count vpc internet-gateways in ca-central-1",
        "count vpc internet-gateways in eu-central-1",
        "count vpc internet-gateways in eu-west-1",
        "count vpc internet-gateways in sa-east-1",
        "count vpc internet-gateways in us-east-1",
        "count vpc internet-gateways in us-east-2",
        "count vpc internet-gateways in us-west-1",
        "count vpc internet-gateways in us-west-2",
        "count VPC network ACLs per region",
        "count vpc network-acls in eu-west-1",
        "count VPC route tables per region",
        "count vpc route-tables in eu-west-1",
        "count vpc subnets in ap-northeast-1",
        "count vpc subnets in ap-northeast-2",
        "count vpc subnets in ap-northeast-3",
        "count vpc subnets in ap-south-1",
        "count vpc subnets in ap-southeast-1",
        "count vpc subnets in ap-southeast-2",
        "count vpc subnets in ca-central-1",
        "count vpc subnets in eu-central-1",
        "count vpc subnets in eu-north-1",
        "count vpc subnets in eu-west-1",
        "count vpc subnets in eu-west-2",
        "count vpc subnets in eu-west-3",
        "count vpc subnets in sa-east-1",
        "count vpc subnets in us-east-1",
        "count vpc subnets in us-east-2",
        "count vpc subnets in us-west-1",
        "count vpc subnets in us-west-2",
        "count vpc vpcs in eu-west-1",
        "count VPCs and subnets per region",
        "count VPCs and VPC subnets per region",
        "count VPCs in ap-south-1 vs ap-east-1",
        "count VPCs per account",
        "count VPCs per region",
        "give me VPCs in eu-west-1",
        "how many VPC endpoints per region",
        "how many VPCs per region",
        "list all VPCs",
        "list vpc subents",
        "show me all vpc resources",
        "show me default network ACLs",
        "show me default VPCs",
        "show me internet gateways",
        "show me network ACLs in us-east-1",
        "show me network ACLs with is_default true",
        "show me non-default VPCs",
        "show me route tables with main true",
        "show me subnets in ap-northeast-1",
        "show me subnets in ap-northeast-2",
        "show me subnets in ap-northeast-3",
        "show me subnets in ap-south-1",
        "show me subnets in ap-southeast-1",
        "show me subnets in ap-southeast-2",
        "show me subnets in ca-central-1",
        "show me subnets in eu-central-1",
        "show me subnets in eu-central-2",
        "show me subnets in eu-north-1",
        "show me subnets in us-east-1",
        "show me subnets in us-east-1 with map public IP enabled",
        "show me subnets in vpc-12345678",
        "show me subnets with auto-assign public IP enabled",
        "show me subnets with available IP count greater than 100",
        "show me subnets with available IP count greater than 200",
        "show me subnets with available_ip_count less than 50",
        "show me subnets with map public IP on launch enabled",
        "show me subnets with state available",
        "show me subnets without auto-assign public IP",
        "show me subnets without route tables",
        "show me the VPC CIDRs",
        "show me VPC DHCP options",
        "show me vpc dhcp-optionss in ap-northeast-1",
        "show me vpc dhcp-optionss in ap-northeast-2",
        "show me vpc dhcp-optionss in ap-northeast-3",
        "show me vpc dhcp-optionss in ap-south-1",
        "show me vpc dhcp-optionss in ap-southeast-1",
        "show me vpc dhcp-optionss in ap-southeast-2",
        "show me vpc dhcp-optionss in ca-central-1",
        "show me vpc dhcp-optionss in eu-central-1",
        "show me vpc dhcp-optionss in eu-north-1",
        "show me vpc dhcp-optionss in eu-west-1",
        "show me vpc dhcp-optionss in eu-west-2",
        "show me vpc dhcp-optionss in eu-west-3",
        "show me vpc dhcp-optionss in sa-east-1",
        "show me vpc dhcp-optionss in us-east-1",
        "show me vpc dhcp-optionss in us-east-2",
        "show me vpc dhcp-optionss in us-west-1",
        "show me vpc dhcp-optionss in us-west-2",
        "show me VPC endpoints for S3",
        "show me VPC internet gateways",
        "show me vpc internet-gateways in ap-northeast-1",
        "show me vpc internet-gateways in ap-northeast-2",
        "show me vpc internet-gateways in ap-northeast-3",
        "show me vpc internet-gateways in ap-south-1",
        "show me vpc internet-gateways in ap-southeast-1",
        "show me vpc internet-gateways in ap-southeast-2",
        "show me vpc internet-gateways in ca-central-1",
        "show me vpc internet-gateways in eu-central-1",
        "show me vpc internet-gateways in eu-north-1",
        "show me vpc internet-gateways in eu-west-1",
        "show me vpc internet-gateways in eu-west-2",
        "show me vpc internet-gateways in eu-west-3",
        "show me vpc internet-gateways in sa-east-1",
        "show me vpc internet-gateways in us-east-1",
        "show me vpc internet-gateways in us-east-2",
        "show me vpc internet-gateways in us-west-1",
        "show me vpc internet-gateways in us-west-2",
        "show me VPC network ACLs",
        "show me vpc network-acls in ap-northeast-1",
        "show me vpc network-acls in ap-northeast-2",
        "show me vpc network-acls in ap-northeast-3",
        "show me vpc network-acls in ap-south-1",
        "show me vpc network-acls in ap-southeast-1",
        "show me vpc network-acls in ap-southeast-2",
        "show me vpc network-acls in ca-central-1",
        "show me vpc network-acls in eu-central-1",
        "show me vpc network-acls in eu-north-1",
        "show me vpc network-acls in eu-west-1",
        "show me vpc network-acls in eu-west-2",
        "show me vpc network-acls in eu-west-3",
        "show me vpc network-acls in sa-east-1",
        "show me vpc network-acls in us-east-1",
        "show me vpc network-acls in us-east-2",
        "show me vpc network-acls in us-west-1",
        "show me vpc network-acls in us-west-2",
        "show me VPC route tables",
        "show me vpc route-tables in ap-northeast-1",
        "show me vpc route-tables in ap-northeast-2",
        "show me vpc route-tables in ap-northeast-3",
        "show me vpc route-tables in ap-south-1",
        "show me vpc route-tables in ap-southeast-1",
        "show me vpc route-tables in ap-southeast-2",
        "show me vpc route-tables in ca-central-1",
        "show me vpc route-tables in eu-central-1",
        "show me vpc route-tables in eu-north-1",
        "show me vpc route-tables in eu-west-1",
        "show me vpc route-tables in eu-west-2",
        "show me vpc route-tables in eu-west-3",
        "show me vpc route-tables in sa-east-1",
        "show me vpc route-tables in us-east-1",
        "show me vpc route-tables in us-east-2",
        "show me vpc route-tables in us-west-1",
        "show me vpc route-tables in us-west-2",
        "show me VPC subnets",
        "show me vpc subnets in ap-northeast-1",
        "show me vpc subnets in ap-northeast-2",
        "show me vpc subnets in ap-northeast-3",
        "show me vpc subnets in ap-south-1",
        "show me vpc subnets in ap-southeast-1",
        "show me vpc subnets in ap-southeast-2",
        "show me vpc subnets in ca-central-1",
        "show me vpc subnets in eu-central-1",
        "show me vpc subnets in eu-central-2",
        "show me vpc subnets in eu-north-1",
        "show me vpc subnets in eu-south-1",
        "show me vpc subnets in eu-south-2",
        "show me vpc subnets in eu-west-1",
        "show me vpc subnets in eu-west-2",
        "show me vpc subnets in eu-west-3",
        "show me vpc subnets in sa-east-1",
        "show me vpc subnets in us-east-1",
        "show me vpc subnets in us-east-2",
        "show me vpc subnets in us-west-1",
        "show me vpc subnets in us-west-2",
        "show me vpc vpcs in ap-northeast-1",
        "show me vpc vpcs in ap-northeast-2",
        "show me vpc vpcs in ap-northeast-3",
        "show me vpc vpcs in ap-south-1",
        "show me vpc vpcs in ap-southeast-1",
        "show me vpc vpcs in ap-southeast-2",
        "show me vpc vpcs in ca-central-1",
        "show me vpc vpcs in eu-central-1",
        "show me vpc vpcs in eu-north-1",
        "show me vpc vpcs in eu-west-1",
        "show me vpc vpcs in eu-west-2",
        "show me vpc vpcs in eu-west-3",
        "show me vpc vpcs in sa-east-1",
        "show me vpc vpcs in us-east-1",
        "show me vpc vpcs in us-east-2",
        "show me vpc vpcs in us-west-1",
        "show me vpc vpcs in us-west-2",
        "show me VPCs",
        "show me VPCs in ap-northeast-1",
        "show me VPCs in ap-northeast-2",
        "show me VPCs in ap-northeast-3",
        "show me VPCs in ap-south-1",
        "show me VPCs in ap-southeast-1",
        "show me VPCs in ap-southeast-2",
        "show me VPCs in ca-central-1",
        "show me VPCs in eu-central-1",
        "show me VPCs in eu-central-2",
        "show me VPCs in eu-north-1",
        "show me VPCs in eu-west-1 that are non-default",
        "show me VPCs in us-east-1 that are default",
        "show me VPCs sorted by name",
        "show me VPCs sorted by region",
        "show me VPCs with CIDR 10.0.0.0/16",
        "show me VPCs with CIDR containing 172.31",
        "show me VPCs with is_default 0",
        "show me VPCs with is_default 1",
        "show me VPCs with state available",
        "show me VPCs without any subnets",
        "what VPCs are in my account",
        "which VPCs are default",
    ],
    "wafv2": [
        "count all wafv2 resources",
        "count WAF web ACLs per region",
        "show me all wafv2 resources",
        "show me WAF web ACLs",
        "show me WAF web ACLs in global",
        "what WAF web ACLs do I have",
    ],
}


def list_services():
    """Return list of (service_key, display_name, count) sorted by count desc."""
    result = []
    for svc, qs in _EXAMPLES.items():
        display = _DISPLAY_NAMES.get(svc, svc)
        result.append((svc, display, len(qs)))
    result.sort(key=lambda x: -x[2])
    return result


def list_questions(service):
    """Return list of questions for a service. Returns None if not found."""
    svc = resolve_service(service)
    if svc:
        return list(_EXAMPLES[svc])
    return None


def resolve_service(service):
    """Resolve a service name to its canonical key. Returns None if not found."""
    if service in _EXAMPLES:
        return service
    sl = service.lower()
    for svc in _EXAMPLES:
        if svc.lower() == sl:
            return svc
    for svc, display in _DISPLAY_NAMES.items():
        if svc in _EXAMPLES and display.lower() == sl:
            return svc
    return None


def search(term):
    """Search questions by substring. Returns list of (service, question)."""
    tl = term.lower()
    results = []
    for svc, qs in _EXAMPLES.items():
        for q in qs:
            if tl in q.lower():
                results.append((svc, q))
    return results


def total_count():
    """Return total number of examples."""
    return sum(len(qs) for qs in _EXAMPLES.values())

